# Plateforme minimale requise
platform :ios, '12.0'

# Désactiver les statistiques CocoaPods (optionnel)
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

# Configuration des cibles
target 'Runner' do
  # Utiliser les frameworks pour éviter certains problèmes de compatibilité
  use_frameworks!
  use_modular_headers!

  # Installer les dépendances Flutter
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end